(function() {
  "use strict";
  window.DEVQUEST_VISUALS = {
    items: [
      { id: "trace-values", game: "predict-output", title: "Follow the values", category: "Code reading", icon: "🧮", intro: "Watch each item travel through the loop. The total changes one small step at a time.", code: ["for (const item of items) {", "  sum += item.price * item.qty;", "}", "return sum;"], steps: [
        { label: "Start with the basket", focus: [0], nodes: [{ icon: "📦", title: "Item A", value: "$3 × 2" }, { icon: "📦", title: "Item B", value: "$4 × 1" }], takeaway: "Two items go into the loop, one at a time.", caption: "Read the actual inputs first. Price and quantity are separate values." },
        { label: "Multiply each item", focus: [1], nodes: [{ icon: "✖️", title: "Item A", value: "3 × 2 = 6" }, { icon: "✖️", title: "Item B", value: "4 × 1 = 4" }], takeaway: "The loop adds 6, then 4.", caption: "The multiplication happens before each item is added to sum." },
        { label: "Return the total", focus: [3], nodes: [{ icon: "➕", title: "Running total", value: "6 + 4" }, { icon: "✨", title: "Answer", value: "10" }], takeaway: "The function returns 10.", caption: "Trace the changes instead of guessing from the last line." }
      ] },
      { id: "exact-match", game: "explain-code", title: "A Set remembers exact matches", category: "Code reading", icon: "🧺", intro: "See how a Set keeps the first exact email string and skips a repeat.", code: ["if (seen.has(user.email)) return false;", "seen.add(user.email);", "return true;"], steps: [
        { label: "First email arrives", focus: [0, 1], nodes: [{ icon: "📨", title: "Mina", value: "mina@demo.test" }, { icon: "🧺", title: "Seen set", value: "empty" }], takeaway: "The address is new, so this user stays.", caption: "The Set starts empty. The first exact string is added." },
        { label: "Same string again", focus: [0], nodes: [{ icon: "📨", title: "Next user", value: "mina@demo.test" }, { icon: "🔎", title: "Set check", value: "already seen" }], takeaway: "The duplicate is filtered out.", caption: "A matching string returns false from the filter callback." },
        { label: "Different capitalization", focus: [0, 1], nodes: [{ icon: "📨", title: "Next user", value: "Mina@demo.test" }, { icon: "🧺", title: "Exact match?", value: "no" }], takeaway: "Uppercase M is a different string here.", caption: "This code is case-sensitive. It does not normalize email addresses." }
      ] },
      { id: "quantity-bug", game: "spot-bug", title: "Price needs quantity", category: "Debugging", icon: "🐛", intro: "Watch a cart total go wrong when the code forgets that an item can have a quantity.", code: ["cart.items.push(item);", "cart.total += item.price;", "return cart;"], steps: [
        { label: "Add three mugs", focus: [0], nodes: [{ icon: "☕", title: "Mugs", value: "3 × $8" }, { icon: "🛒", title: "Cart", value: "$0" }], takeaway: "The cart receives one line item with quantity 3.", caption: "The input says three mugs, so the total must include all three." },
        { label: "The bug runs", focus: [1], nodes: [{ icon: "☕", title: "Price", value: "$8" }, { icon: "🛒", title: "Buggy total", value: "$8" }], takeaway: "Only one price was added.", caption: "This line reads price but never multiplies by item.qty." },
        { label: "Fix the calculation", focus: [1], nodes: [{ icon: "☕", title: "Price × quantity", value: "$8 × 3" }, { icon: "✅", title: "Correct total", value: "$24" }], takeaway: "Compare the calculation with the ticket and its edge cases.", caption: "The fix uses price times quantity, then tests the multi-item case." }
      ] },
      { id: "spec-check", game: "spec-check", title: "Match each rule to evidence", category: "Review skills", icon: "🧾", intro: "A passing test is only one clue. Check every promise against what the code actually does.", code: ["if (!coupon.active) return error;", "if (coupon.expired) return error;", "const total = cart.total - coupon.amount;", "return { total };"], steps: [
        { label: "List the promises", focus: [], nodes: [{ icon: "🔂", title: "One use", value: "required" }, { icon: "⏰", title: "Not expired", value: "required" }, { icon: "0️⃣", title: "Floor at zero", value: "required" }], takeaway: "Each acceptance criterion needs a check.", caption: "Turn the ticket into separate, testable promises before reviewing." },
        { label: "Find evidence", focus: [0, 1], nodes: [{ icon: "✅", title: "Active check", value: "present" }, { icon: "✅", title: "Expiry check", value: "present" }, { icon: "❓", title: "One-use check", value: "missing" }], takeaway: "The diff checks active and expired status only.", caption: "Point to a line or test for every criterion. A guess is not evidence." },
        { label: "Spot the missing boundary", focus: [2, 3], nodes: [{ icon: "⚠️", title: "Reuse guard", value: "missing" }, { icon: "📉", title: "Total floor", value: "missing" }, { icon: "🧹", title: "Extra rename", value: "out of scope" }], takeaway: "Flag the gaps and ask to split unrelated changes.", caption: "Tests passing does not prove an untested requirement." }
      ] },
      { id: "safe-login", game: "ai-code-audit", title: "Review the login path", category: "Security", icon: "🔐", intro: "Follow a login request through a risky password check and an unsafe response.", code: ["if (user.password === input) {", "  return { token: user.apiKey };", "}"], steps: [
        { label: "A password arrives", focus: [0], nodes: [{ icon: "🔑", title: "Submitted value", value: "raw password" }, { icon: "🗄️", title: "Stored value", value: "plain text?" }], takeaway: "Passwords should be verified against a salted hash.", caption: "A server should not store or compare a readable password." },
        { label: "The response leaks", focus: [1], nodes: [{ icon: "🗝️", title: "Internal API key", value: "server secret" }, { icon: "📤", title: "Client response", value: "leaked" }], takeaway: "Do not send internal secrets to the browser.", caption: "Even a correct password check does not make this response safe." },
        { label: "Use a safer path", focus: [], nodes: [{ icon: "🧂", title: "Password", value: "verify hash" }, { icon: "🎟️", title: "Response", value: "limited session" }], takeaway: "Verify securely and return only what the client needs.", caption: "Review the whole path: storage, comparison, and response." }
      ] },
      { id: "test-gaps", game: "tests-that-lie", title: "Green tests can miss a rule", category: "Testing", icon: "🧪", intro: "A test suite can be green while an important path has never been tried.", code: ["test('valid coupon', ...);", "test('expired coupon', ...);", "// same customer tries twice?", "// big discount goes below zero?"], steps: [
        { label: "What got tested?", focus: [0, 1], nodes: [{ icon: "✅", title: "Valid coupon", value: "covered" }, { icon: "✅", title: "Expired coupon", value: "covered" }], takeaway: "These two checks pass.", caption: "Green means the cases that ran matched their expected result." },
        { label: "What is still unknown?", focus: [2], nodes: [{ icon: "👤", title: "Same customer", value: "reuse" }, { icon: "🔂", title: "Second try", value: "not checked" }], takeaway: "The single-use requirement has a hole.", caption: "Add a test that repeats the coupon for the same customer." },
        { label: "Test the boundary", focus: [3], nodes: [{ icon: "💸", title: "Cart", value: "$50" }, { icon: "🏷️", title: "Discount", value: "$80" }, { icon: "🧪", title: "Expected", value: "$0, not −$30" }], takeaway: "Add edge cases that match the ticket.", caption: "A small boundary test can catch a bug the happy path never sees." }
      ] },
      { id: "clear-spec", game: "spec-builder", title: "Turn a vague ask into a clear spec", category: "Prompting", icon: "🧭", intro: "A clear request gives the builder guardrails and tells you how to check the result.", code: ["Request: make coupons better", "Rule: once per customer", "Rule: reject expired codes", "Check: total stays at least 0"], steps: [
        { label: "Start with a fuzzy ask", focus: [0], nodes: [{ icon: "💬", title: "Request", value: "make it better" }, { icon: "🤖", title: "Builder guess", value: "too many choices" }], takeaway: "Vague requests leave important behavior undefined.", caption: "The AI may fill gaps with its own assumptions." },
        { label: "Add observable rules", focus: [1, 2], nodes: [{ icon: "🔂", title: "Use limit", value: "one per person" }, { icon: "⏰", title: "Expiry", value: "reject" }], takeaway: "Write behavior that a reviewer can verify.", caption: "Concrete rules make expected behavior easier to test." },
        { label: "Add a check and boundary", focus: [3], nodes: [{ icon: "🧪", title: "Test", value: "each rule" }, { icon: "🚧", title: "Scope", value: "no unrelated rename" }, { icon: "✅", title: "Review", value: "clear" }], takeaway: "State the outcome, checks, and scope limit.", caption: "Now the change has a target and a fence around it." }
      ] },
      { id: "safe-query", game: "security-spot", title: "Keep input out of the command", category: "Security", icon: "🛡️", intro: "See how string concatenation can let user input change a query, and how parameters keep it separate.", code: ["const email = req.query.email;", "const sql = `... '${email}'`;", "db.query(sql);"], steps: [
        { label: "Input is ordinary data", focus: [0], nodes: [{ icon: "👤", title: "Email field", value: "typed by user" }, { icon: "📨", title: "Server", value: "untrusted input" }], takeaway: "User input must be treated as data.", caption: "The server cannot assume a browser value is harmless." },
        { label: "The string is assembled", focus: [1], nodes: [{ icon: "🧩", title: "SQL command", value: "query + input" }, { icon: "⚠️", title: "Boundary", value: "blended" }], takeaway: "Concatenation can change the meaning of a command.", caption: "When data is placed inside command text, special input can escape its intended spot." },
        { label: "Bind a parameter", focus: [2], nodes: [{ icon: "📄", title: "SQL template", value: "fixed command" }, { icon: "📦", title: "Email value", value: "separate data" }, { icon: "🔒", title: "Database", value: "safe boundary" }], takeaway: "Use parameterized queries and check access rights.", caption: "The database receives the command and its values separately." }
      ] },
      { id: "debug-loop", game: "debug-detective", title: "Debug with a small repro", category: "Debugging", icon: "🔍", intro: "A tiny repeatable example helps you find the cause before changing code.", code: ["reproduce the failure", "trace the values", "isolate the cause", "fix, then verify"], steps: [
        { label: "Reproduce", focus: [0], nodes: [{ icon: "🛒", title: "Cart", value: "$20" }, { icon: "🏷️", title: "Coupon", value: "$35" }, { icon: "🐛", title: "Observed", value: "−$15" }], takeaway: "Make the failure happen reliably.", caption: "Use the smallest inputs that still show the bug." },
        { label: "Trace and isolate", focus: [1, 2], nodes: [{ icon: "➖", title: "Calculation", value: "20 − 35" }, { icon: "🔎", title: "Cause", value: "no lower bound" }], takeaway: "The coupon branch is the only path that changes the total.", caption: "Evidence narrows the cause before you edit anything." },
        { label: "Fix and verify", focus: [3], nodes: [{ icon: "🛠️", title: "Change", value: "clamp at 0" }, { icon: "🧪", title: "Retest", value: "same repro passes" }], takeaway: "Verify the original failure and a nearby edge case.", caption: "A fix is stronger when the failing example becomes a regression test." }
      ] },
      { id: "floor-boundary", game: "code-fix", title: "Protect the zero boundary", category: "Testing", icon: "🧱", intro: "A discount can be bigger than the cart. Keep the result inside the allowed range.", code: ["function applyCoupon(total, discount) {", "  return total - discount;", "}", "Math.max(0, total - discount)"], steps: [
        { label: "Normal discount", focus: [1], nodes: [{ icon: "🛒", title: "Cart", value: "$100" }, { icon: "🏷️", title: "Discount", value: "$20" }, { icon: "✅", title: "Result", value: "$80" }], takeaway: "The ordinary case behaves as expected.", caption: "Happy paths are useful, but they are not the whole rule." },
        { label: "Discount exceeds cart", focus: [1], nodes: [{ icon: "🛒", title: "Cart", value: "$50" }, { icon: "🏷️", title: "Discount", value: "$80" }, { icon: "⚠️", title: "Result", value: "−$30" }], takeaway: "The original code crosses the allowed boundary.", caption: "The requirement says the total can never go below zero." },
        { label: "Clamp and test", focus: [3], nodes: [{ icon: "🧱", title: "Lower bound", value: "$0" }, { icon: "🧪", title: "Normal", value: "$80" }, { icon: "🎯", title: "Oversized", value: "$0" }], takeaway: "A clear boundary plus edge tests makes the rule stick.", caption: "Use the smallest safe change, then test regular and oversized discounts." }
      ] },
      { id: "review-diff", game: "review-pr", title: "Review the diff, keep the good parts", category: "Review skills", icon: "🧑‍⚖️", intro: "Separate missing behavior from correct work and unrelated edits.", code: ["// expiry check is present", "// no per-customer use check", "// total may go below 0", "// unrelated helper rename"], steps: [
        { label: "Check the ticket", focus: [0, 1, 2], nodes: [{ icon: "⏰", title: "Expiry rule", value: "met" }, { icon: "🔂", title: "One use", value: "missing" }, { icon: "0️⃣", title: "No negative total", value: "missing" }], takeaway: "Review the behavior against each ticket rule.", caption: "A review should name concrete gaps, not just say something feels wrong." },
        { label: "Notice scope creep", focus: [3], nodes: [{ icon: "🧹", title: "Helper rename", value: "unrelated" }, { icon: "✂️", title: "Suggestion", value: "split it out" }], takeaway: "Keep the current change focused and easy to inspect.", caption: "Unrelated edits can be their own follow-up change." },
        { label: "Send a useful review", focus: [1, 2, 3], nodes: [{ icon: "💬", title: "Specific gap", value: "show evidence" }, { icon: "✅", title: "Correct piece", value: "keep it" }, { icon: "🤝", title: "Tone", value: "helpful" }], takeaway: "Flag real gaps and preserve correct work.", caption: "A good review helps the teammate make the change safe." }
      ] },
      { id: "incident-steps", game: "incident", title: "Stabilize before investigating", category: "Teamwork", icon: "🚦", intro: "When checkout is hurting customers, reduce impact, verify recovery, then share confirmed facts.", code: ["1. stabilize", "2. verify recovery", "3. communicate facts", "4. investigate and prevent"], steps: [
        { label: "Impact is climbing", focus: [0], nodes: [{ icon: "📈", title: "Error rate", value: "38%" }, { icon: "🛒", title: "Checkout", value: "affected" }, { icon: "🚨", title: "Priority", value: "reduce impact" }], takeaway: "Act to limit customer impact first.", caption: "Avoid guessing about blame while the service is still failing." },
        { label: "Roll back and verify", focus: [1], nodes: [{ icon: "↩️", title: "Coupon path", value: "disabled" }, { icon: "📉", title: "Errors", value: "falling" }, { icon: "✅", title: "Recovery", value: "confirmed" }], takeaway: "Check that users can complete checkout again.", caption: "A rollback is a step, not proof of recovery. Verify it." },
        { label: "Share facts, then learn", focus: [2, 3], nodes: [{ icon: "📣", title: "Update", value: "confirmed facts" }, { icon: "🔍", title: "Investigate", value: "after stability" }, { icon: "🧰", title: "Prevent", value: "add guard + test" }], takeaway: "Communicate clearly, investigate, and prevent a repeat.", caption: "Keep updates factual and follow up with a test or safeguard." }
      ] },
      { id: "verify-claims", game: "hallucination-hunter", title: "Plausible is not verified", category: "AI skills", icon: "🕵️", intro: "Match every assistant claim with an actual line of evidence.", code: ["signature: fetchRecords(): Promise<Record[]>", "docs: no retry option shown", "claim: retries 3 times by default"], steps: [
        { label: "Read the evidence", focus: [0], nodes: [{ icon: "📄", title: "Signature", value: "Promise<Record[]>" }, { icon: "🔎", title: "Visible fact", value: "returns a promise" }], takeaway: "The displayed signature supports this claim.", caption: "Point to the evidence before accepting a statement." },
        { label: "Look for the retry rule", focus: [1], nodes: [{ icon: "📚", title: "Docs shown", value: "no retry option" }, { icon: "🤖", title: "AI claim", value: "3 retries" }], takeaway: "No evidence supports the retry claim yet.", caption: "A familiar-sounding detail can still be invented." },
        { label: "Verify the unknown", focus: [2], nodes: [{ icon: "❓", title: "Claim", value: "unverified" }, { icon: "🧪", title: "Next move", value: "check docs/code" }, { icon: "✅", title: "Status", value: "then decide" }], takeaway: "Mark it unknown until the source confirms it.", caption: "Verify unfamiliar behavior in the real docs or implementation." }
      ] },
      { id: "prompt-rails", game: "prompt-fix", title: "Give the AI useful guardrails", category: "AI skills", icon: "🪄", intro: "A strong prompt says what success looks like, how to check it, and what should stay untouched.", code: ["Outcome: one coupon use per customer", "Invalid: reject expired codes", "Boundary: total is at least 0", "Scope: don't rename helpers", "Check: add tests for each rule"], steps: [
        { label: "A fuzzy prompt", focus: [0], nodes: [{ icon: "💬", title: "Ask", value: "make it better" }, { icon: "🎲", title: "Result", value: "AI has to guess" }], takeaway: "Missing detail creates room for unwanted assumptions.", caption: "The model cannot infer every product rule from a vague request." },
        { label: "Describe success", focus: [0, 1, 2], nodes: [{ icon: "🔂", title: "Behavior", value: "one per person" }, { icon: "⏰", title: "Invalid", value: "reject expired" }, { icon: "🧱", title: "Boundary", value: "never below 0" }], takeaway: "Concrete outcomes make the task reviewable.", caption: "Use rules someone can observe and test." },
        { label: "Add checks and a fence", focus: [3, 4], nodes: [{ icon: "🚧", title: "Scope", value: "no helper rename" }, { icon: "🧪", title: "Tests", value: "cover each rule" }, { icon: "🎯", title: "Change", value: "small and clear" }], takeaway: "Tell the AI what to change and what to leave alone.", caption: "Good prompts include outcomes, checks, and scope limits." }
      ] }
    ]
  };
})();
