window.SKILLQUEST_WORLDS = [
  { name: "New Hire Island", icon: "🏝️", theme: "Chat, listen, ask questions and find your workday rhythm" },
  { name: "Teamwork Town", icon: "🏘️", theme: "Work together, share ideas and sort out little mix-ups" },
  { name: "Brainpower Bay", icon: "🧠", theme: "Solve puzzles, spot risks and make thoughtful calls" },
  { name: "Captain’s Corner", icon: "🧢", theme: "Help a team move forward with care and confidence" },
  { name: "Big Boss Adventures", icon: "🐉", theme: "Bring your skills together for bigger story missions" }
];

var skillquestEntries = [
  [
    ["Choose the right channel", "Communication", "A teammate asks whether a meeting is at 2 or 3. At the same time, a project partner says a deadline may slip.", "Reply to the quick time question in chat, then arrange a short two-way discussion about the deadline risk.", "A quick fact can be answered quickly; a changing deadline needs a conversation and a clear next step.", "Match the channel to the work: quick facts can be chat, complex issues need back-and-forth.", "Bundling both topics for later leaves a simple question unanswered and delays a risk discussion."],
    ["Clarify the request", "Questioning", "Your manager writes, “Can you sort out the launch notes?” You are not sure who needs them or by when.", "Ask who the notes are for, what they need to include, and when they are due.", "A few focused questions prevent rework and show that you are ready to take ownership.", "Before starting a vague task, confirm the audience, outcome and deadline.", "Guessing what “sort out” means can produce the wrong work."],
    ["Listen and summarize", "Active listening", "A coworker says they are frustrated because a project keeps changing. You want to help, but you do not yet understand the main issue.", "Listen without interrupting, then summarize what you heard and ask if you understood correctly.", "Checking your understanding gives your coworker room to correct details before you suggest a solution.", "Reflect the concern before offering advice: “It sounds like… Did I get that right?”", "Jumping straight to advice may miss what is actually bothering them."],
    ["Write a clear update", "Clear writing", "Your project update is a long paragraph. Teammates need to know what is done, what is blocked, and what happens next.", "Write a short update with status, blocker or risk, and the next action with an owner.", "Readers can quickly find what changed and what they need to do.", "Put the key update first, then name the next action and owner.", "A long message without a clear next step makes it harder to act."],
    ["Respond to feedback", "Receiving feedback", "A teammate points out that your report is missing an important figure. You feel a little defensive.", "Thank them, ask where the figure should go, and confirm when you will update the report.", "You turn feedback into a clear improvement action without needing to agree with every detail immediately.", "Listen for the useful detail, clarify it, and agree on a next step.", "Defending yourself before understanding the issue can stop a useful conversation."],
    ["Ask for help early", "Help-seeking", "A task is blocked because you cannot access a shared file. The deadline is tomorrow.", "Explain what you tried, name the blocker, and ask the file owner or support contact for access now.", "A specific early request gives others time to unblock you and helps the team adjust if needed.", "When asking for help, include the goal, what you tried, and the specific blocker.", "Waiting until the deadline makes a small access issue harder to solve."],
    ["Plan your first day", "Prioritization", "You have a client update due today, a team document due Friday, and an optional webinar starting now.", "Check the client update deadline and impact, schedule focused time for it, then plan the document and webinar around it.", "Prioritizing by urgency and impact helps you protect the commitment with the greatest near-term consequence.", "List deadlines and impact before choosing what to do first.", "Choosing tasks by convenience alone can put the most important commitment at risk."],
    ["Protect focus time", "Time management", "A colleague asks for help with a non-urgent question while you are finishing a time-sensitive report.", "Acknowledge them, say when you can help, and return to the report until that time.", "You stay respectful while making your availability clear and protecting focused work.", "A kind boundary can include a time you will reconnect.", "Dropping the report immediately may put a commitment at risk."],
    ["Handle a missed message", "Accountability", "You notice you missed a message asking for a document yesterday. The teammate has not followed up yet.", "Own the delay, send the document or a realistic delivery time, and ask whether the timing still works.", "A direct update rebuilds clarity and gives the other person a chance to adjust.", "Acknowledge the miss without a long excuse; share the next step.", "Staying quiet makes the teammate guess whether the request is being handled."],
    ["First-week check-in", "Self-awareness", "Your first week is ending. Your manager asks how things are going, and you have one question and one learning goal.", "Share one thing you completed, ask your question, and name a specific skill you want to practice next.", "A focused check-in helps your manager support you and shows how you are learning.", "Bring one update, one question and one small goal to a check-in.", "Saying only “everything is fine” may hide a simple question that could be resolved early."]
  ],
  [
    ["Share the airtime", "Inclusive communication", "In a team discussion, two people have spoken several times while a quieter teammate has not had a chance to contribute.", "Pause and invite the teammate to share their view, while making it clear they can pass.", "You make room for another perspective without putting someone on the spot.", "Invite input without demanding it: “Would you like to add anything?”", "Moving on without checking can leave useful perspectives unheard."],
    ["Agree on ownership", "Role clarity", "You and a coworker both thought the other person was sending the client summary. The deadline is approaching.", "Clarify who will send it, what the summary needs, and the exact handoff time.", "A named owner and time remove ambiguity and reduce duplicate work.", "End a handoff with a person, an action and a time.", "Assuming the other person will handle it could leave the client waiting."],
    ["Give useful feedback", "Constructive feedback", "A teammate’s draft has a confusing section that may cause readers to misunderstand the recommendation.", "Describe the section you mean, explain the effect on readers, and suggest one concrete improvement.", "Specific feedback about the work is easier to use than a judgement about the person.", "Talk about a specific example, its impact, and a possible next step.", "A vague comment like “this is bad” does not tell them how to improve it."],
    ["Receive a different view", "Openness", "A teammate disagrees with your plan and suggests a different approach. The decision has not been made yet.", "Ask what concern or evidence led them to the alternative, then compare both plans against the shared goal.", "Understanding the reason for disagreement may reveal a risk or a better option.", "Get curious about the other view before defending your own.", "Rejecting the idea immediately can close off useful information."],
    ["Repair a misunderstanding", "Empathy", "A short message you sent sounded abrupt to a colleague. They tell you it came across as dismissive.", "Acknowledge how it landed, clarify your intent briefly, and ask what would help move the work forward.", "Recognizing impact keeps the focus on repairing the working relationship.", "Intent and impact can differ; acknowledge the impact before explaining.", "Arguing that they should not feel that way can deepen the misunderstanding."],
    ["Coordinate a handoff", "Collaboration", "A teammate takes over your task while you are away. They need to know what is complete and what could go wrong.", "Share the goal, current status, open decisions, risks, and the next contact or action.", "The next person can continue without reconstructing the history or missing a risk.", "A good handoff includes status, open questions, risks and next steps.", "Sending only a file link leaves important context out."],
    ["Resolve a small conflict", "Conflict resolution", "Two teammates prefer different tools for the same task. Both approaches could work, but the team needs to choose today.", "Agree on the goal and compare the options against shared criteria such as access, time and team support.", "A shared criterion moves the conversation from personal preference to the work that matters.", "Name what success looks like before comparing options.", "Arguing for a preference without a shared goal can keep the disagreement going."],
    ["Work across time zones", "Distributed teamwork", "You need a colleague in another time zone to review a draft, but your working hours overlap for only a short time.", "Send the context, a specific review request, the deadline, and where they can leave comments asynchronously.", "The colleague can act without waiting for another live meeting.", "For async work, include enough context and a clear response-by time.", "Sending “please review” without a deadline or focus creates avoidable back-and-forth."],
    ["Respond to exclusion", "Inclusion", "During a meeting, a teammate’s idea is overlooked. A few minutes later another person repeats the same idea and gets credit.", "Credit the original contribution and bring the discussion back to the idea, then check in privately if appropriate.", "You restore context without turning the moment into a public confrontation.", "Name the contribution and keep the conversation moving respectfully.", "Ignoring the pattern may signal that the contribution did not matter."],
    ["Team retrospective", "Shared improvement", "A project has just finished. The team has five minutes to reflect before moving to the next task.", "Name one thing to keep, one thing to change, and one small action with an owner.", "A concrete action makes reflection useful and gives the team something to revisit.", "Keep the review forward-looking: what helped, what got in the way, what will we try?", "Listing complaints without an owner or next action rarely changes the process."]
  ],
  [
    ["Define the actual problem", "Problem framing", "The team wants to buy a new tool because weekly reports arrive late. No one has checked where the delay starts.", "Map the current steps and identify where time is being lost before choosing a solution.", "Understanding the cause keeps the team from solving the wrong problem.", "Separate the observed problem from assumptions about its cause.", "Buying a tool immediately may add cost without fixing the bottleneck."],
    ["Find the missing information", "Information gathering", "A request says a customer is unhappy, but gives no detail about the issue, impact, or response already sent.", "Ask what happened, how it affected the customer, and what has already been promised.", "These details help the team respond accurately and avoid conflicting commitments.", "Ask for the few facts that change what you should do next.", "Replying with a guess may make the problem worse."],
    ["Sort facts from guesses", "Critical thinking", "An incident note says, “The update failed because Alex changed the file.” The log only confirms that the file changed before the failure.", "Separate the confirmed sequence from the assumed cause and check the logs or ask involved teammates.", "A careful distinction protects the investigation from blame and false conclusions.", "Label what you know, what you suspect, and what evidence would confirm it.", "Repeating an unverified cause can damage trust and misdirect the fix."],
    ["Compare options", "Decision-making", "You can ship a basic fix today or a complete redesign next month. The customer needs a reliable workaround this week.", "Compare the options against the immediate customer need, risk, effort and a review point.", "Using shared criteria makes the trade-off visible and helps the team choose deliberately.", "Name the goal and trade-offs before selecting a path.", "Choosing only by speed or only by completeness can overlook the main need."],
    ["Prioritize a changing queue", "Adaptability", "A new urgent request arrives while you are halfway through another task. Both requesters expect an update today.", "Check impact and deadlines, agree which item moves first, and tell the affected person what is changing.", "Replanning transparently helps the team avoid silent delays and conflicting assumptions.", "When priorities shift, make the trade-off visible and update people.", "Adding the new request without moving anything can create an unrealistic plan."],
    ["Notice a risk early", "Risk awareness", "A supplier has not confirmed delivery, and the project schedule depends on that delivery next week.", "Raise the dependency now, describe its impact, and suggest a backup or decision date.", "Early notice gives the team time to reduce the risk instead of reacting at the last minute.", "Pair a risk statement with an impact and a possible mitigation.", "Waiting for certainty may leave too little time to respond."],
    ["Run a small experiment", "Experimentation", "Your team wants to change its entire onboarding process because one new hire found the guide confusing.", "Test one revised section with a small group and ask what they understood before changing the whole process.", "A small test gives the team evidence at low cost and lets it improve the change.", "Try the smallest test that can answer the key question.", "A full rollout based on one experience may create more work than needed."],
    ["Handle incomplete data", "Judgement", "You need to recommend a project option, but one usage report will not arrive until next week.", "Make a provisional recommendation, state the missing data and explain what would change your decision.", "The team can make progress while understanding the limits of the recommendation.", "Be clear about confidence, assumptions and a review trigger.", "Presenting a guess as certain can create misplaced confidence."],
    ["Learn from a mistake", "Learning mindset", "A scheduled reminder failed and a deliverable was missed. The team is discussing what to change.", "Trace the process, find where the reminder could fail, and agree on a safeguard with an owner.", "Looking at the process helps prevent a repeat without reducing the review to blame.", "Ask how the system allowed the miss and what safeguard would help.", "Focusing only on who forgot may not fix the process weakness."],
    ["Make the call", "Decision ownership", "The team has compared two workable options. Someone needs to decide so the next task can start.", "Name the decision, explain the main reason, record the trade-off, and set a time to review it.", "A clear decision and review point allow action while preserving a chance to adjust.", "A decision can be revisited when new evidence appears; record when.", "Leaving the decision open after discussion can stall the work."]
  ],
  [
    ["Set a shared goal", "Goal setting", "A project brief says, “Improve the new starter experience.” Different teammates have different ideas about what success means.", "Agree on a visible outcome, who owns each action, and when the team will check progress.", "A shared measure and owner turn a broad intention into coordinated work.", "Define the outcome, owner and check-in before assigning tasks.", "Starting with different assumptions can send the team in several directions."],
    ["Delegate with context", "Delegation", "You are leading a small project and want a teammate to prepare the first customer interview plan.", "Explain the purpose, deadline, decisions they can make, available support, and where to bring questions.", "The teammate knows what success looks like and where they have room to decide.", "Delegation works better with purpose, boundaries and support.", "Giving only a deadline can leave the person unsure how to proceed."],
    ["Coach instead of taking over", "Coaching", "A teammate tells you they are stuck on a report. You could finish it faster yourself, but they want to learn.", "Ask what they have tried and what the next small step might be, then offer support if needed.", "A useful question can help them build confidence while keeping help available.", "Ask before taking over: “What have you tried, and what feels unclear?”", "Doing it for them may solve today’s task but miss a chance to build skill."],
    ["Run a focused meeting", "Facilitation", "A project meeting has twenty minutes and needs to settle one open decision plus assign follow-up tasks.", "State the outcome and time, guide discussion toward the decision, and close by confirming owners and actions.", "A focused agenda and clear close help everyone use the meeting time well.", "End meetings by restating the decision, owner and next step.", "Letting the conversation wander may leave the key decision unresolved."],
    ["Support someone under pressure", "Empathy and support", "A teammate says, “I cannot keep up with this workload.” You are not their manager, but you can listen and help raise the issue.", "Listen, ask what feels most urgent, and help them identify the right person to discuss capacity with.", "You take the concern seriously while respecting your role and connecting them with support.", "Listen without minimizing; offer to help raise workload or support needs.", "Saying “everyone is busy” can make someone less likely to ask for help."],
    ["Communicate a change", "Change communication", "A process is changing next month, but some details are still being decided. Teammates are asking what will happen.", "Explain what is confirmed, what is still open, why it is changing, and when you will share an update.", "Clear boundaries around known and unknown details reduce speculation.", "Say what you know, what is undecided, and when the next update is due.", "Filling gaps with guesses can create expectations that may not be met."],
    ["Make an ethical pause", "Ethical judgement", "A teammate suggests sharing a customer spreadsheet with a wider group to speed up review. You are unsure whether everyone should see it.", "Pause the share, check the relevant data policy or owner, and use the least access needed.", "A short pause can protect sensitive information while finding a safe way to complete the work.", "When data access is unclear, verify before sharing and limit access.", "Sharing first and checking later may expose information unnecessarily."],
    ["Balance competing needs", "Stakeholder management", "A customer asks for a feature by Friday, but the team has no capacity to build it by then.", "Clarify the customer’s underlying need, explain the constraint honestly, and offer a feasible option or decision date.", "The response respects the customer without making a promise the team cannot keep.", "Understand the need and present realistic options with clear timing.", "Agreeing to an impossible date can harm trust later."],
    ["Address a performance issue", "Accountability with care", "A teammate missed a commitment that affected your work. You need to discuss how to coordinate next time.", "Speak privately, describe the specific impact, ask what happened, and agree on a next step together.", "A private, fact-based conversation gives room to understand causes and improve coordination.", "Focus on the commitment and impact, then listen before deciding next steps.", "Calling them out in a group can make the conversation defensive."],
    ["Build a team decision", "Leadership and collaboration", "A team needs to choose a launch date. Different roles see different risks, and one person owns the final call.", "Gather the relevant views, make the decision owner clear, and record the reason and follow-up.", "People can contribute while understanding who decides and how the choice will be reviewed.", "Invite input, clarify decision rights, and document the rationale.", "Continuing discussion without a decision owner may leave the team stuck."]
  ],
  [
    ["The shifting deadline", "Prioritization", "A deadline moves forward. A teammate is blocked, and a stakeholder asks when the project will be ready.", "Check the blocker and impact, update the plan with the team, then give the stakeholder a verified status and next update time.", "You coordinate before promising a new date and give the stakeholder clear information.", "When dates change, align internally and communicate what is confirmed.", "Sending a confident date before checking the blocker can create another missed commitment."],
    ["The unhappy customer", "Empathy and problem-solving", "A customer is upset about a service issue. Your team is still investigating what caused it.", "Acknowledge the impact, clarify what they need now, share what is confirmed, and set a time for the next update.", "The customer is heard and knows what will happen even while the cause is still being checked.", "Separate empathy, confirmed facts and the next communication time.", "Guessing at a cause or promising a fix can undermine trust."],
    ["The cross-team launch", "Collaboration", "Two teams have different launch requirements, and ownership for one final check is unclear.", "Bring the owners together, list the conflicting requirements, agree who decides, and confirm the launch checklist.", "A named owner and explicit requirements reduce the chance of a last-minute gap.", "Resolve ownership and criteria before treating the launch as ready.", "Assuming the other team owns the check can leave a critical step undone."],
    ["The meeting that goes off track", "Facilitation", "A tense discussion has drifted into old complaints, but the group still needs to decide how to handle the current issue.", "Acknowledge the concern, restate the decision needed, and invite each person to offer a relevant option.", "You recognize the emotion while helping the group return to a useful next step.", "Name the purpose and make room for concerns that affect the decision.", "Forcing the group to move on without hearing the concern may increase tension."],
    ["The data concern", "Ethics and risk", "A teammate wants to copy personal information into a shared tracker so more people can help investigate an issue.", "Pause the copy, check the approved process, and share only the minimum necessary with authorized people.", "The issue can be investigated while reducing unnecessary exposure of personal information.", "Use approved channels and minimum necessary access for sensitive data.", "A convenient shared tracker may expose information beyond the right audience."],
    ["The sudden outage", "Calm communication", "A service is unavailable. The cause is unknown, several teams are investigating, and customers are asking for updates.", "Assign a coordinator, share only verified updates, and set a regular time for the next communication.", "Clear roles and steady verified updates help teams act without spreading guesses.", "In an incident, state what is known, what is being checked, and when you will update.", "Speculating publicly about the cause can confuse customers and slow response."],
    ["The overloaded team", "Leadership and prioritization", "Your team has more work than capacity this week. A new request arrives with an ambitious deadline.", "Review commitments with the team, identify what can move, and discuss scope or timing with the requester.", "Making capacity visible creates a realistic plan and gives the requester options.", "Do not add work invisibly; show the trade-offs and negotiate scope.", "Accepting the new work without changing anything can overload the team."],
    ["The difficult handoff", "Collaboration and accountability", "A project moves to another team tomorrow. Some tasks are complete, but two risks and one decision are still open.", "Walk through the status, open risks, decision owner and next check-in with the receiving team.", "A direct handoff helps the next team own the work without hidden gaps.", "Make open work visible and confirm who owns each next action.", "Marking the project “done” before sharing the open risks can cause surprises."],
    ["The recovery plan", "Problem-solving and learning", "A delivery failed. The customer needs an immediate recovery plan, and the team needs to understand how to prevent a repeat.", "Stabilize the customer impact, agree on owners and timing, then review contributing factors without blame.", "Recovery comes first, followed by a process review that can reduce the chance of recurrence.", "Separate immediate containment from later learning and prevention.", "Jumping to blame before restoring service can delay recovery and hide system causes."],
    ["Your first leadership challenge", "Integrated leadership", "You are leading a short project. Midway through, a key requirement changes and the original plan no longer fits.", "Bring the team together, restate the goal, compare scope and timing options, assign owners, and set a review point.", "You combine listening, prioritization and clear ownership while adapting the plan.", "When conditions change, revisit the goal, trade-offs, owners and next check-in.", "Trying to preserve the old plan without discussion can create confusion and rushed work."]
  ]
];

var skillquestWrongOptions = [
  ["Make an assumption and start without checking what they need.", "Wait for another message before responding."],
  ["Decide for the group and move on without checking others' views.", "Avoid the conversation and hope the tension fades."],
  ["Choose the first solution before checking facts or trade-offs.", "Wait for complete certainty even if work is blocked."],
  ["Give a directive before hearing concerns or context.", "Leave the uncomfortable issue for someone else to address."],
  ["Act alone and send an unverified promise.", "Pause all communication until someone else has a complete answer."]
];

window.SKILLQUEST_LEVELS = [];
skillquestEntries.forEach(function(worldEntries, worldIndex) {
  worldEntries.forEach(function(entry, index) {
    var levelId = worldIndex * 10 + index + 1;
    var correctPosition = (levelId - 1) % 3;
    var wrongs = skillquestWrongOptions[worldIndex];
    var choices = [];
    for (var slot = 0; slot < 3; slot += 1) {
      if (slot === correctPosition) choices.push(entry[3]);
      else choices.push(wrongs[slot < correctPosition ? 0 : 1]);
    }
    window.SKILLQUEST_LEVELS.push({
      id: levelId,
      world: worldIndex,
      title: entry[0],
      skill: entry[1],
      story: entry[2],
      choices: choices,
      correct: correctPosition,
      why: entry[4],
      tip: entry[5],
      risk: entry[6]
    });
  });
});

delete window.skillquestEntries;
